### ISSUE TITLE
Readme characters are not universal

### ISSUE THREAD

**Issue by almeidaraul** [kmmelcher/cartoonfight#18]
[Screenshot](https://almeidaraul.github.io/temp/screenshot_cf.png)

Saw it on latest version of Firefox, Ubuntu 20.04.1

**Comment by kmmelcher** [comment]
I'm open to suggestions if you find out universal arrow characters

**Comment by kmmelcher** [comment]
I saw the solution for this issue here: https://stackoverflow.com/questions/54954544/how-do-i-show-the-up-and-down-arrow-keyboard-key-in-github-markdown 
But this led me to find this amazing list of emojis: https://gist.github.com/rxaviers/7360908 
Already updated the README, what do you think @almeidaraul ?

**Comment by almeidaraul** [comment]
@kmmelcher put more emojis
